#############################################################################
# This playbook sets up a WordPress web server using the LAMP stack
#
# To use this playbook:
#   ansible-playbook playbook.yaml -i hosts.yaml -u <sudo user> --ask-become
#############################################################################

---
- hosts: all
  become: true
  vars:
    mysql_root_password: "root"
    mysql_db: "wordpress"
    mysql_user: "khewitt"
    mysql_password: "password"

    http_host: "ansible-site"
    http_conf: "ansible-site.conf"
    http_port: "80"

  tasks:
# System
    - name: Install LAMP Packages
      apt: 
        name: "{{ item }}" 
        update_cache: yes 
        state: latest
      loop:
      - apache2
      - mysql-server
      - python3-pymysql
      - php
      - php-mysql
      - libapache2-mod-php

    - name: Install PHP Extensions
      apt: 
        name: "{{ item }}" 
        update_cache: yes
        state: latest
      loop:
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip

# Apache
    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0775'

    - name: Set up Apache VirtualHost
      template:
        src: "./apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache

    - name: Enable rewrite module
      shell: /usr/sbin/a2enmod rewrite
      notify: Reload Apache

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

# MySQL
    - name: Set the root password
      no_log: true
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Creates database for WordPress
      no_log: true
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL user for WordPress
      no_log: true
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

# Firewall
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

# WordPress
    - name: Download/Unpack WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/{{ http_host }}"
        remote_src: yes
        creates: "/var/www/{{ http_host }}/wordpress"

    - name: Set ownership and permissions recusively
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: '1750'
     
    - name: Set up wp-config
      template:
        src: "./wp-config.php.j2"
        dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded